---
- name: Ensure server prerequisite playbook is executed
  hosts: servers
  roles:
    - linuxhq.linux.selinux
    - linuxhq.linux.rush
    - linuxhq.linux.group
    - linuxhq.linux.user
    - linuxhq.linux.authorized_key
    - linuxhq.linux.pam_ssh_agent_auth
    - linuxhq.linux.sudo
    - linuxhq.linux.file
...
