---
cf_dns:
  - zone: "{{ cf_zone }}"
    records:
      - record: '@'
        proxied: false
        type: A
        value: 5.39.88.56

      - record: '@'
        proxied: false
        type: A
        value: 208.87.241.207

      - record: _dmarc
        proxied: false
        type: TXT
        value: 'v=DMARC1; p=reject; sp=reject; adkim=s; aspf=s;'

      - record: '*._domainkey'
        proxied: false
        type: TXT
        value: 'v=DKIM1; p='

      - record: '@'
        proxied: false
        type: TXT
        value: 'v=spf1 -all'
...
