---
- name: Ensure cloud playbook is executed
  hosts: cloud
  roles:
    - linuxhq.aws.aws_caller_info
    - linuxhq.aws.aws_region_info
    - linuxhq.aws.aws_az_info
    - linuxhq.aws.service_quota
    - linuxhq.aws.iam_account_alias
    - linuxhq.aws.iam_password_policy
    - linuxhq.aws.iam_managed_policy
    - linuxhq.aws.iam_role
    - linuxhq.aws.iam_user
    - linuxhq.aws.iam_group
    - linuxhq.aws.s3_bucket
    - linuxhq.aws.s3_lifecycle
    - linuxhq.aws.ec2_vpc_net
    - linuxhq.aws.ec2_vpc_dhcp_option
    - linuxhq.aws.ec2_vpc_igw
    - linuxhq.aws.ec2_vpc_subnet
    - linuxhq.aws.ec2_vpc_nat_gateway
    - linuxhq.aws.ec2_vpc_route_table
    - linuxhq.aws.ec2_key
    - linuxhq.aws.ec2_security_group
...
