---
- name: Ensure cloud playbook is executed
  hosts: cloud
  roles:
    - linuxhq.aws.iam_user
    - linuxhq.aws.iam_group
    - linuxhq.aws.vpc
    - linuxhq.aws.internet_gateway
    - linuxhq.aws.subnet
    - linuxhq.aws.route_table
...
