---
cf_page_rules:
  - zone_id: "{{ _cf_zone_id[cf_zone] }}"
    rules:
      - actions:
          - id: forwarding_url
            value:
              status_code: 301
              url: https://github.com/tkimball83
        priority: 1
        targets:
          - constraint:
              operator: matches
              value: "*{{ cf_zone }}/*"
            target: url
...
