---
cf_dns:
  - zone: "{{ cf_zone }}"
    records:
      - record: '@'
        proxied: true
        type: A
        value: 8.8.8.8

      - record: dkim02._domainkey
        proxied: false
        type: CNAME
        value: dkim02._domainkey.simplelogin.co

      - record: dkim03._domainkey
        proxied: false
        type: CNAME
        value: dkim03._domainkey.simplelogin.co

      - record: dkim._domainkey
        proxied: false
        type: CNAME
        value: dkim._domainkey.simplelogin.co

      - record: www
        proxied: true
        type: CNAME
        value: "{{ cf_zone }}"

      - record: '@'
        priority: 20
        proxied: false
        type: MX
        value: mx2.simplelogin.co

      - record: '@'
        priority: 10
        proxied: false
        type: MX
        value: mx1.simplelogin.co

      - record: _dmarc
        proxied: false
        type: TXT
        value: 'v=DMARC1; p=quarantine; pct=100; adkim=s; aspf=s'

      - record: '@'
        proxied: false
        type: TXT
        value: 'v=spf1 include:simplelogin.co ~all'

      - record: '@'
        proxied: false
        type: TXT
        value: 'sl-verification=cuayzlhbmgtsxigourlkawtyggiouy'
...
