---
ec2_security_group_list:
  - name: linuxhq-ssh
    rules:
      - cidr_ip: 0.0.0.0/0
        ports:
          - 22
        proto: tcp
    rules_egress:
      - cidr_ip: 0.0.0.0/0
        proto: -1
    vpc_id: "{{ _ec2_vpc_net_info_id[aws_vpc] }}"

  - name: linuxhq-https
    rules:
      - cidr_ip: 0.0.0.0/0
        ports:
          - 443
        proto: tcp
    rules_egress:
      - cidr_ip: 0.0.0.0/0
        proto: -1
    vpc_id: "{{ _ec2_vpc_net_info_id[aws_vpc] }}"
...
