---
ec2_vpc_subnet_list:
  - name: "{{ aws_vpc }}-pub-{{ _aws_az_info_list_s.0 }}"
    az: "{{ aws_region ~ _aws_az_info_list_s.0 }}"
    cidr: "{{ aws_network | ansible.utils.ipsubnet(27, 0) }}"
    vpc_id: "{{ _ec2_vpc_net_info_id[aws_vpc] }}"

  - name: "{{ aws_vpc }}-pub-{{ _aws_az_info_list_s.1 }}"
    az: "{{ aws_region ~ _aws_az_info_list_s.1 }}"
    cidr: "{{ aws_network | ansible.utils.ipsubnet(27, 1) }}"
    vpc_id: "{{ _ec2_vpc_net_info_id[aws_vpc] }}"

  - name: "{{ aws_vpc }}-pub-{{ _aws_az_info_list_s.2 }}"
    az: "{{ aws_region ~ _aws_az_info_list_s.2 }}"
    cidr: "{{ aws_network | ansible.utils.ipsubnet(27, 2) }}"
    vpc_id: "{{ _ec2_vpc_net_info_id[aws_vpc] }}"

  - name: "{{ aws_vpc }}-pvt-{{ _aws_az_info_list_s.0 }}"
    az: "{{ aws_region ~ _aws_az_info_list_s.0 }}"
    cidr: "{{ aws_network | ansible.utils.ipsubnet(27, 3) }}"
    vpc_id: "{{ _ec2_vpc_net_info_id[aws_vpc] }}"

  - name: "{{ aws_vpc }}-pvt-{{ _aws_az_info_list_s.1 }}"
    az: "{{ aws_region ~ _aws_az_info_list_s.1 }}"
    cidr: "{{ aws_network | ansible.utils.ipsubnet(27, 4) }}"
    vpc_id: "{{ _ec2_vpc_net_info_id[aws_vpc] }}"

  - name: "{{ aws_vpc }}-pvt-{{ _aws_az_info_list_s.2 }}"
    az: "{{ aws_region ~ _aws_az_info_list_s.2 }}"
    cidr: "{{ aws_network | ansible.utils.ipsubnet(27, 5) }}"
    vpc_id: "{{ _ec2_vpc_net_info_id[aws_vpc] }}"
...
