---
ec2_vpc_nat_gateway_list:
  - name: "{{ aws_vpc }}-pub-{{ _aws_az_info_list_s.0 }}"
    if_exist_do_not_create: true
    subnet_id: "{{ _ec2_vpc_subnet_info_subnet_id[aws_vpc ~ '-pub-' ~ _aws_az_info_list_s.0] }}"
    wait: true

  - name: "{{ aws_vpc }}-pub-{{ _aws_az_info_list_s.1 }}"
    if_exist_do_not_create: true
    subnet_id: "{{ _ec2_vpc_subnet_info_subnet_id[aws_vpc ~ '-pub-' ~ _aws_az_info_list_s.1] }}"
    wait: true

  - name: "{{ aws_vpc }}-pub-{{ _aws_az_info_list_s.2 }}"
    if_exist_do_not_create: true
    subnet_id: "{{ _ec2_vpc_subnet_info_subnet_id[aws_vpc ~ '-pub-' ~ _aws_az_info_list_s.2] }}"
    wait: true
...
