---
ec2_vpc_prefix_list_entries:
  - name: cloudflare-ipv4
    entries:
      "{{ lookup('ansible.builtin.url',
                 'https://www.cloudflare.com/ips-v4',
                 wantlist=true) }}"

  - name: cloudflare-ipv6
    address_family: IPv6
    entries:
      "{{ lookup('ansible.builtin.url',
                 'https://www.cloudflare.com/ips-v6',
                 wantlist=true) }}"

  - name: "{{ aws_vpc }}"
    entries:
      - "{{ aws_network }}"
...
