---
ec2_vpc_route_table_list:
  - name: "{{ aws_vpc }}-pub-{{ _aws_az_info_list_s.0 }}"
    routes:
      - dest: '0.0.0.0/0'
        gateway_id: igw
    subnets:
      - "{{ _ec2_vpc_subnet_info_dict[aws_vpc ~ '-pub-' ~ _aws_az_info_list_s.0].id }}"
    vpc_id: "{{ _ec2_vpc_net_info_dict[aws_vpc].id }}"

  - name: "{{ aws_vpc }}-pub-{{ _aws_az_info_list_s.1 }}"
    routes:
      - dest: '0.0.0.0/0'
        gateway_id: igw
    subnets:
      - "{{ _ec2_vpc_subnet_info_dict[aws_vpc ~ '-pub-' ~ _aws_az_info_list_s.1].id }}"
    vpc_id: "{{ _ec2_vpc_net_info_dict[aws_vpc].id }}"

  - name: "{{ aws_vpc }}-pub-{{ _aws_az_info_list_s.2 }}"
    routes:
      - dest: '0.0.0.0/0'
        gateway_id: igw
    subnets:
      - "{{ _ec2_vpc_subnet_info_dict[aws_vpc ~ '-pub-' ~ _aws_az_info_list_s.2].id }}"
    vpc_id: "{{ _ec2_vpc_net_info_dict[aws_vpc].id }}"

  - name: "{{ aws_vpc }}-pvt-{{ _aws_az_info_list_s.0 }}"
    routes:
      - dest: '0.0.0.0/0'
        gateway_id:
          "{{ _ec2_vpc_nat_gateway_info_dict[aws_vpc ~ '-pub-' ~ _aws_az_info_list_s.0].nat_gateway_id }}"
    subnets:
      - "{{ _ec2_vpc_subnet_info_dict[aws_vpc ~ '-pvt-' ~ _aws_az_info_list_s.0].id }}"
    vpc_id: "{{ _ec2_vpc_net_info_dict[aws_vpc].id }}"

  - name: "{{ aws_vpc }}-pvt-{{ _aws_az_info_list_s.1 }}"
    routes:
      - dest: '0.0.0.0/0'
        gateway_id:
          "{{ _ec2_vpc_nat_gateway_info_dict[aws_vpc ~ '-pub-' ~ _aws_az_info_list_s.1].nat_gateway_id }}"
    subnets:
      - "{{ _ec2_vpc_subnet_info_dict[aws_vpc ~ '-pvt-' ~ _aws_az_info_list_s.1].id }}"
    vpc_id: "{{ _ec2_vpc_net_info_dict[aws_vpc].id }}"

  - name: "{{ aws_vpc }}-pvt-{{ _aws_az_info_list_s.2 }}"
    routes:
      - dest: '0.0.0.0/0'
        gateway_id:
          "{{ _ec2_vpc_nat_gateway_info_dict[aws_vpc ~ '-pub-' ~ _aws_az_info_list_s.2].nat_gateway_id }}"
    subnets:
      - "{{ _ec2_vpc_subnet_info_dict[aws_vpc ~ '-pvt-' ~ _aws_az_info_list_s.2].id }}"
    vpc_id: "{{ _ec2_vpc_net_info_dict[aws_vpc].id }}"
...
