---
iam_password_policy_allow_pw_change: true
iam_password_policy_min_pw_length: 24
iam_password_policy_pw_reuse_prevent: 10
iam_password_policy_require_lowercase: true
iam_password_policy_require_numbers: true
iam_password_policy_require_symbols: true
iam_password_policy_require_uppercase: true
...
