---
iam_role_list:
  - name: LinuxHQEKSNodeGroup
    assume_role_policy_document:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action:
            - sts:AssumeRole
    managed_policies:
      - AmazonEC2ContainerRegistryReadOnly
      - AmazonEKS_CNI_Policy
      - AmazonEKSWorkerNodePolicy
      - AmazonSSMManagedInstanceCore
      - AmazonS3ReadOnlyAccess
      - CloudWatchAgentServerPolicy
...
