---
kms_key_list:
  - name: linuxhq/ssm
    enable_key_rotation: true
    policy:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            AWS:
              - "arn:aws:iam::{{ _aws_caller_info_account }}:root"
          Action:
            - kms:*
          Resource:
            - '*'
        - Effect: Allow
          Principal:
            AWS: '*'
          Action:
            - kms:Decrypt
          Resource:
            - '*'
          Condition:
            ArnLike:
              'aws:PrincipalArn':
                - "arn:aws:iam::{{ _aws_caller_info_account }}:role/LinuxHQInstanceProfile*"
        - Effect: Allow
          Principal:
            Service: "logs.{{ aws_region }}.amazonaws.com"
          Action:
            - kms:Decrypt*
            - kms:Describe*
            - kms:Encrypt*
            - kms:GenerateKeyData*
            - kms:ReEncrypt*
          Resource:
            - '*'
          Condition:
            ArnLike:
              'kms:EncryptionContext:aws:logs:arn':
                "arn:aws:logs:{{ aws_region }}:{{ _aws_caller_info_account }}:log-group:/linuxhq/ssm/sessions"
...
