---
s3_lifecycle_list:
  - name: "{{ _aws_caller_info_account }}-{{ aws_region }}-linuxhq-backups"
    rules:
      - rule_id: linuxhq-30d-glacier
        transition_days: 30
        prefix: 30d/
        status: enabled
        storage_class: glacier
      - rule_id: linuxhq-90d-glacier
        transition_days: 90
        prefix: 90d/
        status: enabled
        storage_class: glacier
      - rule_id: linuxhq-365d-glacier
        transition_days: 365
        prefix: 365d/
        status: enabled
        storage_class: glacier
...
