---
ssm_parameter_list:
  - name: /linuxhq/openssh/key/pub
    string_type: SecureString
    value: "{{ openssh_key_pub }}"

  - name: /linuxhq/region
    value: "{{ aws_region }}"

  - name: /linuxhq/vpc/id
    value: "{{ _ec2_vpc_net_info_id[aws_vpc] }}"

  - name: /linuxhq/igw/id
    value: "{{ _ec2_vpc_igw_info_internet_gateway_id[aws_vpc] }}"

  - name: "/linuxhq/subnet/pub/{{ _aws_az_info_list_s.0 }}/id"
    value: "{{ _ec2_vpc_subnet_info_subnet_id[aws_vpc ~ '-pub-' ~ _aws_az_info_list_s.0] }}"

  - name: "/linuxhq/subnet/pub/{{ _aws_az_info_list_s.1 }}/id"
    value: "{{ _ec2_vpc_subnet_info_subnet_id[aws_vpc ~ '-pub-' ~ _aws_az_info_list_s.1] }}"

  - name: "/linuxhq/subnet/pub/{{ _aws_az_info_list_s.2 }}/id"
    value: "{{ _ec2_vpc_subnet_info_subnet_id[aws_vpc ~ '-pub-' ~ _aws_az_info_list_s.2] }}"

  - name: "/linuxhq/subnet/pvt/{{ _aws_az_info_list_s.0 }}/id"
    value: "{{ _ec2_vpc_subnet_info_subnet_id[aws_vpc ~ '-pvt-' ~ _aws_az_info_list_s.0] }}"

  - name: "/linuxhq/subnet/pvt/{{ _aws_az_info_list_s.1 }}/id"
    value: "{{ _ec2_vpc_subnet_info_subnet_id[aws_vpc ~ '-pvt-' ~ _aws_az_info_list_s.1] }}"

  - name: "/linuxhq/subnet/pvt/{{ _aws_az_info_list_s.2 }}/id"
    value: "{{ _ec2_vpc_subnet_info_subnet_id[aws_vpc ~ '-pvt-' ~ _aws_az_info_list_s.2] }}"

  - name: "/linuxhq/rtb/pub/{{ _aws_az_info_list_s.0 }}/id"
    value: "{{ _ec2_vpc_route_table_info_route_table_id[aws_vpc ~ '-pub-' ~ _aws_az_info_list_s.0] }}"

  - name: "/linuxhq/rtb/pub/{{ _aws_az_info_list_s.1 }}/id"
    value: "{{ _ec2_vpc_route_table_info_route_table_id[aws_vpc ~ '-pub-' ~ _aws_az_info_list_s.1] }}"

  - name: "/linuxhq/rtb/pub/{{ _aws_az_info_list_s.2 }}/id"
    value: "{{ _ec2_vpc_route_table_info_route_table_id[aws_vpc ~ '-pub-' ~ _aws_az_info_list_s.2] }}"

  - name: "/linuxhq/rtb/pvt/{{ _aws_az_info_list_s.0 }}/id"
    value: "{{ _ec2_vpc_route_table_info_route_table_id[aws_vpc ~ '-pvt-' ~ _aws_az_info_list_s.0] }}"

  - name: "/linuxhq/rtb/pvt/{{ _aws_az_info_list_s.1 }}/id"
    value: "{{ _ec2_vpc_route_table_info_route_table_id[aws_vpc ~ '-pvt-' ~ _aws_az_info_list_s.1] }}"

  - name: "/linuxhq/rtb/pvt/{{ _aws_az_info_list_s.2 }}/id"
    value: "{{ _ec2_vpc_route_table_info_route_table_id[aws_vpc ~ '-pvt-' ~ _aws_az_info_list_s.2] }}"

  - name: /linuxhq/pl/cloudflare-ipv4
    value: "{{ _ec2_vpc_prefix_list_info_prefix_list_id['cloudflare-ipv4'] }}"

  - name: /linuxhq/pl/cloudflare-ipv6
    value: "{{ _ec2_vpc_prefix_list_info_prefix_list_id['cloudflare-ipv6'] }}"

  - name: /linuxhq/pl/linuxhq
    value: "{{ _ec2_vpc_prefix_list_info_prefix_list_id['linuxhq'] }}"
...

