---
dnf_absent:
  - cockpit-ws
  - postfix

dnf_present:
  - bind-utils
  - git
  - iptraf-ng
  - net-tools
  - python3
  - python3-dnf-plugins-core
  - python3-setuptools
  - rsync
  - rsyslog
  - rsyslog-logrotate
  - screen
  - sysstat
  - tcpdump
  - tree

dnf_protected_d:
  - name: shim
    packages:
      - shim-aa64
      - shim-arm
      - shim-ia32
      - shim-x64
...
