---
nmcli:
  - conn_name: "{{ ansible_default_ipv4.interface }}"
    dns4:
      - "{{ ansible_lo.ipv4.address }}"
    ip4: "{{ ansible_default_ipv4.address }}/{{ ansible_default_ipv4.prefix }}"
    gw4: "{{ ansible_default_ipv4.gateway }}"
    method6: ignore
    type: ethernet
...
