---
pta_actions:
  - package_filter: docker-ce
    transaction_state: in
    command: /usr/bin/systemctl restart "docker-compose@*.service"

  - package_filter: kernel
    transaction_state: in
    command: /usr/sbin/grub2-set-default 0

  - package_filter: kernel-lt
    transaction_state: in
    command: /usr/sbin/grub2-set-default 0

  - package_filter: kernel-ml
    transaction_state: in
    command: /usr/sbin/grub2-set-default 0

  - package_filter: util-linux
    transaction_state: in
    command: /usr/bin/chmod -s /usr/bin/su
...
