---
sudo_env_keep:
  - SSH_AUTH_SOCK

sudo_pam:
  - module_interface: auth
    control_flag: sufficient
    module_name: pam_ssh_agent_auth.so
    module_arguments: file=/etc/security/authorized_keys

  - module_interface: auth
    control_flag: include
    module_name: system-auth

  - module_interface: account
    control_flag: include
    module_name: system-auth

  - module_interface: password
    control_flag: include
    module_name: system-auth

  - module_interface: session
    control_flag: include
    module_name: system-auth
...
