---
sysctl_d:
  - name: 99-linuxhq
    parameters:
      fs.protected_hardlinks: 1
      fs.protected_symlinks: 1
      fs.suid_dumpable: 0
      kernel.core_uses_pid: 1
      kernel.dmesg_restrict: 1
      kernel.hung_task_panic: 0
      kernel.hung_task_timeout_secs: 0
      kernel.kexec_load_disabled: 1
      kernel.kptr_restrict: 2
      kernel.panic: 1
      kernel.perf_event_paranoid: 2
      kernel.printk: '4 4 1 7'
      kernel.randomize_va_space: 2
      kernel.softlockup_panic: 0
      kernel.sysrq: 0
      net.core.rmem_max: 2500000
      net.core.wmem_max: 2500000
      net.ipv4.conf.all.accept_redirects: 0
      net.ipv4.conf.all.accept_source_route: 0
      net.ipv6.conf.all.disable_ipv6: 1
      net.ipv4.conf.all.log_martians: 1
      net.ipv4.conf.all.rp_filter: 1
      net.ipv4.conf.all.send_redirects: 0
      net.ipv4.conf.default.accept_redirects: 0
      net.ipv6.conf.default.disable_ipv6: 1
      net.ipv4.conf.default.log_martians: 1
      net.ipv6.conf.lo.disable_ipv6: 1
      net.ipv4.icmp_echo_ignore_broadcasts: 1
      net.ipv4.icmp_ignore_bogus_error_responses: 1
      net.ipv4.tcp_syncookies: 1
      user.max_user_namespaces: 0
...
