---
unbound_forward_zones:
  '.':
    forward-addr:
      - '1.1.1.1@853#cloudflare-dns.com'
      - '1.0.0.1@853#cloudflare-dns.com'
    forward-first: false
    forward-tls-upstream: true

unbound_server:
  interface: 127.0.0.1
  tls-cert-bundle: /etc/pki/tls/certs/ca-bundle.crt
...
