---
unbound_forward_zones:
  '.':
    forward-addr:
      - '8.8.8.8@853#dns.google'
      - '8.8.4.4@853#dns.google'
      - '1.1.1.1@853#cloudflare-dns.com'
      - '1.0.0.1@853#cloudflare-dns.com'
      - '9.9.9.9@853#dns.quad9.net'
      - '149.112.112.112@853#dns.quad9.net'
    forward-first: false
    forward-tls-upstream: true

unbound_server:
  interface: 127.0.0.1
  tls-cert-bundle: /etc/pki/tls/certs/ca-bundle.crt
...
