---
useradd:
  - name: root
    password: "{{ password_root }}"
    shell: /bin/bash
    uid: 0

  - name: tkimball
    append: true
    group: tkimball
    groups:
      - wheel
    password: "{{ password_tkimball }}"
    shell: /bin/bash
    uid: 2000

  - name: linuxhq
    group: linuxhq
    password: '*'
    shell: /usr/sbin/rush
    uid: 3000
...
