---
virtualenv_become: true

virtualenvs:
  - virtualenv: /opt/ansible
    virtualenv_command: /usr/bin/python3.9 -m venv
    name:
      - ansible<9
      - jmespath==1.0.1
      - lxml==4.9.3
      - requests<2.29
      - setuptools
    extra_args: '--no-cache-dir'
...
