---
name: linting
'on':
  push:
    branches: '*'
  pull_request:

jobs:
  ansible-lint:
    name: ansible-lint
    runs-on: ubuntu-latest
    steps:
      - name: Ensure codebase is present
        uses: actions/checkout@v4

      - name: Ensure ansible-lint-action is present
        uses: ansible/ansible-lint@v24

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Ensure codebase is present
        uses: actions/checkout@v4

      - name: Ensure python3 is present
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Ensure yamllint is present
        run: pip install yamllint

      - name: Ensure yamllint is executed
        run: yamllint -s .
...
